import { afterEach, describe, expect, it, vi } from 'vitest'
import { calculateToastDuration, ToastManager } from './toast'
afterEach(() => vi.useRealTimers())
describe('Toast-System', () => {
  it('berechnet dynamische Mindest- und Maximaldauer', () => { expect(calculateToastDuration('')).toBe(3000); expect(calculateToastDuration('länger')).toBeGreaterThan(3000); expect(calculateToastDuration('x'.repeat(1000))).toBe(15000) })
  it('schließt automatisch und respektiert explizite Dauer', () => { vi.useFakeTimers(); const container = document.createElement('div'); const manager = new ToastManager(container); manager.show({ id: 'a', message: 'Text', variant: 'info', durationMs: 20 }); expect(container.children).toHaveLength(1); vi.advanceTimersByTime(20); expect(container.children).toHaveLength(0) })
  it('zeigt höchstens drei, führt Warteschlange nach und aktualisiert Gruppen', () => { const container = document.createElement('div'); const manager = new ToastManager(container); for (let i = 0; i < 4; i += 1) manager.show({ id: String(i), message: String(i), variant: 'progress', persistent: true }); expect(container.children).toHaveLength(3); manager.dismiss('0'); expect(container.children).toHaveLength(3); manager.show({ id: 'new', groupId: '1', message: 'Aktualisiert', variant: 'success' }); expect(container.textContent).toContain('Aktualisiert'); expect(container.children).toHaveLength(3) })
  it('nutzt Rollen und manuelles Schließen', () => { const container = document.createElement('div'); const manager = new ToastManager(container); manager.show({ id: 'e', message: 'Fehler', variant: 'error', persistent: true }); expect(container.querySelector('[role="alert"]')).not.toBeNull(); (container.querySelector('[aria-label="Nachricht schließen"]') as HTMLButtonElement).click(); expect(container.children).toHaveLength(0) })
  it('schließt per Escape und pausiert persistenten Fortschritt', () => { vi.useFakeTimers(); const container = document.createElement('div'); const manager = new ToastManager(container); manager.show({ id: 'p', message: 'Fortschritt', variant: 'progress' }); vi.advanceTimersByTime(20000); expect(container.children).toHaveLength(1); container.firstElementChild?.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); expect(container.children).toHaveLength(0) })
})
