import { beforeEach, describe, expect, it } from 'vitest'
import { readVisibleGpt, redactSensitiveActionConfiguration } from './gptReader'
describe('GPT reader', () => { beforeEach(() => { document.body.innerHTML = '<main><h1>Mein GPT 🤖</h1><p data-gpt-description>Eine Beschreibung</p><span data-gpt-creator>Ada</span><textarea name="instructions">Sei hilfreich.</textarea><button data-conversation-starter>Grüße mich 👋</button><button data-conversation-starter>Grüße mich 👋</button><div data-knowledge-file data-name="wissen.pdf" data-type="PDF" data-size="2 MB"></div><label data-gpt-capability data-capability="web search" aria-checked="true"></label></main>' }); it('liest sichtbare Editorinformationen strukturiert', () => { const result = readVisibleGpt(document, 'gpt-editor'); expect(result).toMatchObject({ name: 'Mein GPT 🤖', description: 'Eine Beschreibung', creator: { name: 'Ada' }, instructions: 'Sei hilfreich.', conversationStarters: ['Grüße mich 👋'], knowledgeFiles: [{ name: 'wissen.pdf', type: 'PDF', sizeLabel: '2 MB', includedInArchive: false }], capabilities: { webSearch: true } }) }); it('erfindet öffentlich keine internen Daten', () => { const result = readVisibleGpt(document, 'gpt-detail'); expect(result?.instructions).toBeUndefined(); expect(result?.knowledgeFiles).toEqual([]); expect(result?.warnings).toHaveLength(1) }); it('redigiert Geheimnisse rekursiv und ohne Beachtung der Großschreibung', () => { expect(redactSensitiveActionConfiguration({ apiKey: 'x', AUTHORIZATION: 'Bearer x', nested: { refreshToken: 'x', safe: 'ok' }, password: 'x', clientSecret: 'x' })).toEqual({ apiKey: '[NICHT EXPORTIERT]', AUTHORIZATION: '[NICHT EXPORTIERT]', nested: { refreshToken: '[NICHT EXPORTIERT]', safe: 'ok' }, password: '[NICHT EXPORTIERT]', clientSecret: '[NICHT EXPORTIERT]' }) }) })

it('liest die reale Detailstruktur ohne main und schließt Navigation aus', () => {
  window.history.replaceState({}, '', '/g/g-69de136277f4819189aa21247ccb1538-english-lerncoach')
  document.body.innerHTML = '<nav><button>Navigation</button></nav><div role="main"><header><button>English Lerncoach</button><button aria-label="Menü">…</button></header><section><h1>English Lerncoach</h1><p>Von Ma Kad</p><p>Ich helfe deutschsprachigen Lernenden, Englisch strukturiert zu verbessern.</p><div data-starter-area><button>Starte meinen Englisch-Einstufungstest.</button><button>Ich habe schon ein Profil. Mach mit der nächsten Lektion...</button><button>Starte meinen Englisch-Einstufungstest.</button></div><button aria-label="Mikrofon">Mikrofon</button><div contenteditable="true" data-placeholder="ChatGPT fragen"></div></section></div>'
  expect(readVisibleGpt(document, 'gpt-detail')).toMatchObject({ exportSource: 'gpt-detail', id: 'g-69de136277f4819189aa21247ccb1538-english-lerncoach', name: 'English Lerncoach', description: 'Ich helfe deutschsprachigen Lernenden, Englisch strukturiert zu verbessern.', creator: { name: 'Ma Kad' }, conversationStarters: ['Starte meinen Englisch-Einstufungstest.', 'Ich habe schon ein Profil. Mach mit der nächsten Lektion...'], instructions: undefined, knowledgeFiles: [] })
})
