import { describe, expect, it, vi } from 'vitest'
import { discoverProject, MAX_PROJECT_CHATS, ProjectChatLimitError, readChatGptProject, safeChatGptUrl } from './projectReader'

function page(path = '/project/pro-1'): void { window.history.replaceState({}, '', path); document.body.innerHTML = `<main data-testid="project-page" data-project-id="pro-1"><h1 data-testid="project-title">Mein Projekt 👋</h1><div data-testid="project-chats"><a href="/c/a">Erster</a><a href="/c/a">Duplikat</a><a href="https://evil.test/c/x">Fremd</a><a href="/c/b">Erster</a></div><div data-testid="project-instructions">Sei präzise.</div><a data-testid="file" download="Grüße.pdf" href="/files/x">Grüße.pdf</a></main>` }
describe('Projektleser', () => {
  it('liest die sichtbare echte Projektchatliste und trennt Titel von Vorschauen', () => {
    const id = 'g-p-69f849e273fc8191ba4b3e1fb3602502'; window.history.replaceState({}, '', `/g/${id}`)
    document.body.innerHTML = `<main><header><h1>KI-TEXT</h1></header><div role="tablist"><button role="tab" aria-selected="true">Chats</button></div><div role="tabpanel"><a href="/g/${id}/c/chat-1"><strong>Englischlernen mit GPT</strong><span>für wen ist dieses Tutorial geeignet?</span></a><a href="/g/${id}/c/chat-2"><strong>Logo für Instagram Account</strong><span>Bitte keine Füllfarbe verwenden.</span></a><a href="/g/${id}/c/chat-3"><strong>Vegan Social Media Strategie</strong><span>fertige Video-Skripte Szene für Szene</span></a><a href="/g/${id}/c/chat-3"><strong>Duplikat</strong></a><a hidden href="/g/${id}/c/hidden">Versteckt</a><a href="/g/g-p-ANDERES-PROJEKT/c/chat-4">Fremdprojekt</a></div></main>`
    expect(readChatGptProject()).toMatchObject({ id, title: 'KI-TEXT', chats: [{ id: 'chat-1', title: 'Englischlernen mit GPT' }, { id: 'chat-2', title: 'Logo für Instagram Account' }, { id: 'chat-3', title: 'Vegan Social Media Strategie' }] })
  })
  it('erkennt ein Projekt mit Name, ID, Chats und Dateien', () => { page(); expect(readChatGptProject()).toMatchObject({ id: 'pro-1', title: 'Mein Projekt 👋', chats: [{ id: 'a', position: 1 }, { id: 'b', position: 2 }], instructions: 'Sei präzise.' }); expect(readChatGptProject()?.files).toHaveLength(1) })
  it('erkennt einen normalen Chat nicht', () => { window.history.replaceState({}, '', '/c/a'); document.body.innerHTML = '<main><h1>Chat</h1></main>'; expect(readChatGptProject()).toBeUndefined() })
  it('nutzt einen Projektnamen-Fallback', () => { page(); document.querySelector('h1')?.remove(); expect(readChatGptProject()?.title).toBe('ChatGPT-Projekt') })
  it('lehnt fremde URLs ab', () => expect(safeChatGptUrl('https://evil.test/c/a')).toBeUndefined())
  it('stellt die Scrollposition wieder her und stoppt stabil', async () => { page(); const container = document.querySelector<HTMLElement>('[data-testid="project-chats"]')!; container.scrollTop = 12; Object.defineProperty(container, 'scrollHeight', { value: 200 }); const wait = vi.fn().mockResolvedValue(undefined); await discoverProject(document, wait); expect(wait).toHaveBeenCalledTimes(3); expect(container.scrollTop).toBe(12) })
  it('erzwingt das Sicherheitslimit', () => { page(); const container = document.querySelector('[data-testid="project-chats"]')!; container.innerHTML = Array.from({ length: MAX_PROJECT_CHATS + 1 }, (_, index) => `<a href="/c/${index}">Chat</a>`).join(''); expect(() => readChatGptProject()).toThrow(ProjectChatLimitError) })
})
